### ISSUE TITLE
当进入二级页面的时候这个图标还在，应该怎么搞？

### ISSUE THREAD

**Issue by zhangdaren** [xiaotimo/uni-app-tabbar#1]
如题， 进入二级页面时，这个icon还存在页面上。而底部导航栏已经隐藏了。

**Comment by xiaotimo** [comment]
只能是进二级页面的时候先把图标隐藏掉，跳转之前执行：`var icon = plus.nativeObj.View.getViewById("icon");
			setTimeout(function() {
				icon.hide();
			}, 100);`
